spring:
  application:
    name: Chatbot
  profiles:
    include: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatbot_db
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000