spring:
  application:
    name: Chatbot
  profiles:
    include: local
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG