spring:
  application:
    name: Chatbot
  profiles:
    include: local
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/chatbot_db}
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000